/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SampleData {
    members: Array<FamilyMember>;
    shoppingItems: Array<ShoppingItem>;
    moodEntries: Array<MoodEntry>;
    mealOptions: Array<MealOption>;
    events: Array<CalendarEvent>;
    chores: Array<Chore>;
}
export interface MoodEntry {
    id: bigint;
    memberId: bigint;
    date: Time;
    mood: string;
    note: string;
    createdAt: Time;
}
export interface Chore {
    id: bigint;
    title: string;
    assignedTo?: bigint;
    isCompleted: boolean;
    createdAt: Time;
    dueDate: Time;
    description: string;
    recurrence: string;
}
export interface ShoppingItem {
    id: bigint;
    isCompleted: boolean;
    name: string;
    createdAt: Time;
    addedBy: bigint;
    quantity: string;
    category: string;
}
export type Time = bigint;
export interface Family {
    id: bigint;
    adminPrincipal: Principal;
    name: string;
    createdAt: Time;
}
export interface InviteDetails {
    familyName: string;
    memberColor: string;
    memberName: string;
    memberAvatarEmoji: string;
}
export interface CalendarEvent {
    id: bigint;
    title: string;
    endDate: Time;
    createdAt: Time;
    description: string;
    memberIds: Array<bigint>;
    startDate: Time;
    eventType: string;
}
export interface FamilyMember {
    id: bigint;
    principal?: Principal;
    isLinked: boolean;
    name: string;
    createdAt: Time;
    color: string;
    role: string;
    inviteCode?: string;
    avatarEmoji: string;
    familyId: bigint;
}
export interface MealOption {
    id: bigint;
    isSelected: boolean;
    scheduledDate: Time;
    votes: Array<bigint>;
    name: string;
    createdAt: Time;
    description: string;
    proposedBy: bigint;
}
export type FamilyStatus = {
    __kind__: "NotLinked";
    NotLinked: null;
} | {
    __kind__: "FamilyMember";
    FamilyMember: {
        memberId: bigint;
        familyId: bigint;
    };
} | {
    __kind__: "FamilyAdmin";
    FamilyAdmin: {
        memberId: bigint;
        familyId: bigint;
    };
};
export interface MealAttendance {
    memberId: bigint;
    date: Time;
    attending: boolean;
}
export interface backendInterface {
    addCalendarEvent(title: string, description: string, startDate: Time, endDate: Time, memberIds: Array<bigint>, eventType: string): Promise<bigint>;
    addChore(title: string, description: string, assignedTo: bigint | null, dueDate: Time, recurrence: string): Promise<bigint>;
    addFamilyMemberWithInvite(name: string, color: string, avatarEmoji: string): Promise<{
        memberId: bigint;
        inviteCode: string;
    }>;
    addMealOption(name: string, description: string, proposedBy: bigint, scheduledDate: Time): Promise<bigint>;
    addMoodEntry(memberId: bigint, mood: string, note: string, date: Time): Promise<bigint>;
    addShoppingItem(name: string, quantity: string, category: string, addedBy: bigint): Promise<bigint>;
    clearAllData(): Promise<boolean>;
    clearCompletedShoppingItems(): Promise<bigint>;
    createFamily(familyName: string, adminName: string, adminColor: string, adminAvatarEmoji: string): Promise<{
        memberId: bigint;
        familyId: bigint;
    }>;
    deleteCalendarEvent(id: bigint): Promise<boolean>;
    deleteChore(id: bigint): Promise<boolean>;
    deleteFamilyMember(id: bigint): Promise<boolean>;
    deleteMealOption(id: bigint): Promise<boolean>;
    deleteMoodEntry(id: bigint): Promise<boolean>;
    deleteShoppingItem(id: bigint): Promise<boolean>;
    generateSampleData(): Promise<SampleData>;
    getAllCalendarEvents(): Promise<Array<CalendarEvent>>;
    getAllChores(): Promise<Array<Chore>>;
    getAllFamilyMembers(): Promise<Array<FamilyMember>>;
    getAllMealOptions(): Promise<Array<MealOption>>;
    getAllMoodEntries(): Promise<Array<MoodEntry>>;
    getAllShoppingItems(): Promise<Array<ShoppingItem>>;
    getCalendarEventsByDateRange(startDate: Time, endDate: Time): Promise<Array<CalendarEvent>>;
    getCalendarEventsByMember(memberId: bigint): Promise<Array<CalendarEvent>>;
    getChoresByMember(memberId: bigint): Promise<Array<Chore>>;
    getDataCounts(): Promise<{
        meals: bigint;
        members: bigint;
        shoppingItems: bigint;
        moodEntries: bigint;
        events: bigint;
        chores: bigint;
    }>;
    getFamilyMember(id: bigint): Promise<FamilyMember | null>;
    getInviteDetails(code: string): Promise<InviteDetails>;
    getMealAttendanceForDate(date: Time): Promise<Array<MealAttendance>>;
    getMealOptionsByDate(date: Time): Promise<Array<MealOption>>;
    getMemberAttendance(date: Time, memberId: bigint): Promise<MealAttendance | null>;
    getMoodEntriesByDateRange(startDate: Time, endDate: Time): Promise<Array<MoodEntry>>;
    getMoodEntriesByMember(memberId: bigint): Promise<Array<MoodEntry>>;
    getMyFamily(): Promise<Family>;
    getMyFamilyStatus(): Promise<FamilyStatus>;
    getMyMember(): Promise<FamilyMember>;
    getShoppingItemsByCategory(category: string): Promise<Array<ShoppingItem>>;
    isAdmin(): Promise<boolean>;
    joinFamilyWithCode(inviteCode: string): Promise<{
        memberId: bigint;
        familyId: bigint;
    }>;
    regenerateInviteCode(memberId: bigint): Promise<string>;
    selectMeal(mealId: bigint): Promise<MealOption>;
    setMealAttendance(date: Time, memberId: bigint, attending: boolean): Promise<MealAttendance>;
    toggleChoreComplete(id: bigint): Promise<Chore>;
    toggleShoppingItemComplete(id: bigint): Promise<ShoppingItem>;
    updateCalendarEvent(id: bigint, title: string, description: string, startDate: Time, endDate: Time, memberIds: Array<bigint>, eventType: string): Promise<CalendarEvent>;
    updateChore(id: bigint, title: string, description: string, assignedTo: bigint | null, dueDate: Time, recurrence: string): Promise<Chore>;
    updateFamilyMember(id: bigint, name: string, color: string, avatarEmoji: string): Promise<FamilyMember>;
    updateMemberRole(id: bigint, newRole: string): Promise<FamilyMember>;
    updateMoodEntry(id: bigint, mood: string, note: string): Promise<MoodEntry>;
    updateShoppingItem(id: bigint, name: string, quantity: string, category: string): Promise<ShoppingItem>;
    voteForMeal(mealId: bigint, memberId: bigint): Promise<MealOption>;
}
import type { CalendarEvent as _CalendarEvent, Chore as _Chore, FamilyMember as _FamilyMember, FamilyStatus as _FamilyStatus, MealAttendance as _MealAttendance, MealOption as _MealOption, MoodEntry as _MoodEntry, SampleData as _SampleData, ShoppingItem as _ShoppingItem, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCalendarEvent(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: Array<bigint>, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addChore(arg0: string, arg1: string, arg2: bigint | null, arg3: Time, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChore(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChore(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async addFamilyMemberWithInvite(arg0: string, arg1: string, arg2: string): Promise<{
        memberId: bigint;
        inviteCode: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addFamilyMemberWithInvite(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFamilyMemberWithInvite(arg0, arg1, arg2);
            return result;
        }
    }
    async addMealOption(arg0: string, arg1: string, arg2: bigint, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMealOption(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMealOption(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMoodEntry(arg0: bigint, arg1: string, arg2: string, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoodEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoodEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addShoppingItem(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoppingItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoppingItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearAllData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async clearCompletedShoppingItems(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCompletedShoppingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCompletedShoppingItems();
            return result;
        }
    }
    async createFamily(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        memberId: bigint;
        familyId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createFamily(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFamily(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteCalendarEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteChore(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChore(arg0);
            return result;
        }
    }
    async deleteFamilyMember(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFamilyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFamilyMember(arg0);
            return result;
        }
    }
    async deleteMealOption(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMealOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMealOption(arg0);
            return result;
        }
    }
    async deleteMoodEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMoodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMoodEntry(arg0);
            return result;
        }
    }
    async deleteShoppingItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShoppingItem(arg0);
            return result;
        }
    }
    async generateSampleData(): Promise<SampleData> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSampleData();
                return from_candid_SampleData_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSampleData();
            return from_candid_SampleData_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCalendarEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCalendarEvents();
            return result;
        }
    }
    async getAllChores(): Promise<Array<Chore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChores();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChores();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFamilyMembers(): Promise<Array<FamilyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFamilyMembers();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFamilyMembers();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMealOptions(): Promise<Array<MealOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMealOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMealOptions();
            return result;
        }
    }
    async getAllMoodEntries(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMoodEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMoodEntries();
            return result;
        }
    }
    async getAllShoppingItems(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShoppingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShoppingItems();
            return result;
        }
    }
    async getCalendarEventsByDateRange(arg0: Time, arg1: Time): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEventsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEventsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getCalendarEventsByMember(arg0: bigint): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEventsByMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEventsByMember(arg0);
            return result;
        }
    }
    async getChoresByMember(arg0: bigint): Promise<Array<Chore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChoresByMember(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChoresByMember(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataCounts(): Promise<{
        meals: bigint;
        members: bigint;
        shoppingItems: bigint;
        moodEntries: bigint;
        events: bigint;
        chores: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataCounts();
            return result;
        }
    }
    async getFamilyMember(arg0: bigint): Promise<FamilyMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyMember(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyMember(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteDetails(arg0: string): Promise<InviteDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteDetails(arg0);
            return result;
        }
    }
    async getMealAttendanceForDate(arg0: Time): Promise<Array<MealAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealAttendanceForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealAttendanceForDate(arg0);
            return result;
        }
    }
    async getMealOptionsByDate(arg0: Time): Promise<Array<MealOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealOptionsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealOptionsByDate(arg0);
            return result;
        }
    }
    async getMemberAttendance(arg0: Time, arg1: bigint): Promise<MealAttendance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberAttendance(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberAttendance(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodEntriesByDateRange(arg0: Time, arg1: Time): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getMoodEntriesByMember(arg0: bigint): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesByMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesByMember(arg0);
            return result;
        }
    }
    async getMyFamily(): Promise<Family> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFamily();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFamily();
            return result;
        }
    }
    async getMyFamilyStatus(): Promise<FamilyStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFamilyStatus();
                return from_candid_FamilyStatus_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFamilyStatus();
            return from_candid_FamilyStatus_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMember(): Promise<FamilyMember> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMember();
                return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMember();
            return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoppingItemsByCategory(arg0: string): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingItemsByCategory(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async joinFamilyWithCode(arg0: string): Promise<{
        memberId: bigint;
        familyId: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinFamilyWithCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinFamilyWithCode(arg0);
            return result;
        }
    }
    async regenerateInviteCode(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateInviteCode(arg0);
            return result;
        }
    }
    async selectMeal(arg0: bigint): Promise<MealOption> {
        if (this.processError) {
            try {
                const result = await this.actor.selectMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectMeal(arg0);
            return result;
        }
    }
    async setMealAttendance(arg0: Time, arg1: bigint, arg2: boolean): Promise<MealAttendance> {
        if (this.processError) {
            try {
                const result = await this.actor.setMealAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMealAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleChoreComplete(arg0: bigint): Promise<Chore> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChoreComplete(arg0);
                return from_candid_Chore_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChoreComplete(arg0);
            return from_candid_Chore_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleShoppingItemComplete(arg0: bigint): Promise<ShoppingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleShoppingItemComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleShoppingItemComplete(arg0);
            return result;
        }
    }
    async updateCalendarEvent(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: Time, arg5: Array<bigint>, arg6: string): Promise<CalendarEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateChore(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null, arg4: Time, arg5: string): Promise<Chore> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_Chore_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChore(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_Chore_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFamilyMember(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<FamilyMember> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFamilyMember(arg0, arg1, arg2, arg3);
                return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFamilyMember(arg0, arg1, arg2, arg3);
            return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMemberRole(arg0: bigint, arg1: string): Promise<FamilyMember> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberRole(arg0, arg1);
                return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberRole(arg0, arg1);
            return from_candid_FamilyMember_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMoodEntry(arg0: bigint, arg1: string, arg2: string): Promise<MoodEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMoodEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMoodEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async updateShoppingItem(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<ShoppingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShoppingItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShoppingItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async voteForMeal(arg0: bigint, arg1: bigint): Promise<MealOption> {
        if (this.processError) {
            try {
                const result = await this.actor.voteForMeal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteForMeal(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Chore_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chore): Chore {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FamilyMember_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyMember): FamilyMember {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_FamilyStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyStatus): FamilyStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SampleData_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleData): SampleData {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FamilyMember]): FamilyMember | null {
    return value.length === 0 ? null : from_candid_FamilyMember_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealAttendance]): MealAttendance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    assignedTo: [] | [bigint];
    isCompleted: boolean;
    createdAt: _Time;
    dueDate: _Time;
    description: string;
    recurrence: string;
}): {
    id: bigint;
    title: string;
    assignedTo?: bigint;
    isCompleted: boolean;
    createdAt: Time;
    dueDate: Time;
    description: string;
    recurrence: string;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.assignedTo)),
        isCompleted: value.isCompleted,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        recurrence: value.recurrence
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<_FamilyMember>;
    shoppingItems: Array<_ShoppingItem>;
    moodEntries: Array<_MoodEntry>;
    mealOptions: Array<_MealOption>;
    events: Array<_CalendarEvent>;
    chores: Array<_Chore>;
}): {
    members: Array<FamilyMember>;
    shoppingItems: Array<ShoppingItem>;
    moodEntries: Array<MoodEntry>;
    mealOptions: Array<MealOption>;
    events: Array<CalendarEvent>;
    chores: Array<Chore>;
} {
    return {
        members: from_candid_vec_n4(_uploadFile, _downloadFile, value.members),
        shoppingItems: value.shoppingItems,
        moodEntries: value.moodEntries,
        mealOptions: value.mealOptions,
        events: value.events,
        chores: from_candid_vec_n9(_uploadFile, _downloadFile, value.chores)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: [] | [Principal];
    isLinked: boolean;
    name: string;
    createdAt: _Time;
    color: string;
    role: string;
    inviteCode: [] | [string];
    avatarEmoji: string;
    familyId: bigint;
}): {
    id: bigint;
    principal?: Principal;
    isLinked: boolean;
    name: string;
    createdAt: Time;
    color: string;
    role: string;
    inviteCode?: string;
    avatarEmoji: string;
    familyId: bigint;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.principal)),
        isLinked: value.isLinked,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        role: value.role,
        inviteCode: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.inviteCode)),
        avatarEmoji: value.avatarEmoji,
        familyId: value.familyId
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NotLinked: null;
} | {
    FamilyMember: {
        memberId: bigint;
        familyId: bigint;
    };
} | {
    FamilyAdmin: {
        memberId: bigint;
        familyId: bigint;
    };
}): {
    __kind__: "NotLinked";
    NotLinked: null;
} | {
    __kind__: "FamilyMember";
    FamilyMember: {
        memberId: bigint;
        familyId: bigint;
    };
} | {
    __kind__: "FamilyAdmin";
    FamilyAdmin: {
        memberId: bigint;
        familyId: bigint;
    };
} {
    return "NotLinked" in value ? {
        __kind__: "NotLinked",
        NotLinked: value.NotLinked
    } : "FamilyMember" in value ? {
        __kind__: "FamilyMember",
        FamilyMember: value.FamilyMember
    } : "FamilyAdmin" in value ? {
        __kind__: "FamilyAdmin",
        FamilyAdmin: value.FamilyAdmin
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FamilyMember>): Array<FamilyMember> {
    return value.map((x)=>from_candid_FamilyMember_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chore>): Array<Chore> {
    return value.map((x)=>from_candid_Chore_n10(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
