/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'createdAt' : Time,
  'description' : string,
  'memberIds' : Array<bigint>,
  'startDate' : Time,
  'eventType' : string,
}
export interface Chore {
  'id' : bigint,
  'title' : string,
  'assignedTo' : [] | [bigint],
  'isCompleted' : boolean,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : string,
  'recurrence' : string,
}
export interface Family {
  'id' : bigint,
  'adminPrincipal' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export interface FamilyMember {
  'id' : bigint,
  'principal' : [] | [Principal],
  'isLinked' : boolean,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
  'role' : string,
  'inviteCode' : [] | [string],
  'avatarEmoji' : string,
  'familyId' : bigint,
}
export type FamilyStatus = { 'NotLinked' : null } |
  { 'FamilyMember' : { 'memberId' : bigint, 'familyId' : bigint } } |
  { 'FamilyAdmin' : { 'memberId' : bigint, 'familyId' : bigint } };
export interface InviteDetails {
  'familyName' : string,
  'memberColor' : string,
  'memberName' : string,
  'memberAvatarEmoji' : string,
}
export interface MealAttendance {
  'memberId' : bigint,
  'date' : Time,
  'attending' : boolean,
}
export interface MealOption {
  'id' : bigint,
  'isSelected' : boolean,
  'scheduledDate' : Time,
  'votes' : Array<bigint>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'proposedBy' : bigint,
}
export interface MoodEntry {
  'id' : bigint,
  'memberId' : bigint,
  'date' : Time,
  'mood' : string,
  'note' : string,
  'createdAt' : Time,
}
export interface SampleData {
  'members' : Array<FamilyMember>,
  'shoppingItems' : Array<ShoppingItem>,
  'moodEntries' : Array<MoodEntry>,
  'mealOptions' : Array<MealOption>,
  'events' : Array<CalendarEvent>,
  'chores' : Array<Chore>,
}
export interface ShoppingItem {
  'id' : bigint,
  'isCompleted' : boolean,
  'name' : string,
  'createdAt' : Time,
  'addedBy' : bigint,
  'quantity' : string,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCalendarEvent' : ActorMethod<
    [string, string, Time, Time, Array<bigint>, string],
    bigint
  >,
  'addChore' : ActorMethod<
    [string, string, [] | [bigint], Time, string],
    bigint
  >,
  'addFamilyMemberWithInvite' : ActorMethod<
    [string, string, string],
    { 'memberId' : bigint, 'inviteCode' : string }
  >,
  'addMealOption' : ActorMethod<[string, string, bigint, Time], bigint>,
  'addMoodEntry' : ActorMethod<[bigint, string, string, Time], bigint>,
  'addShoppingItem' : ActorMethod<[string, string, string, bigint], bigint>,
  'clearAllData' : ActorMethod<[], boolean>,
  'clearCompletedShoppingItems' : ActorMethod<[], bigint>,
  'createFamily' : ActorMethod<
    [string, string, string, string],
    { 'memberId' : bigint, 'familyId' : bigint }
  >,
  'deleteCalendarEvent' : ActorMethod<[bigint], boolean>,
  'deleteChore' : ActorMethod<[bigint], boolean>,
  'deleteFamilyMember' : ActorMethod<[bigint], boolean>,
  'deleteMealOption' : ActorMethod<[bigint], boolean>,
  'deleteMoodEntry' : ActorMethod<[bigint], boolean>,
  'deleteShoppingItem' : ActorMethod<[bigint], boolean>,
  'generateSampleData' : ActorMethod<[], SampleData>,
  'getAllCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getAllChores' : ActorMethod<[], Array<Chore>>,
  'getAllFamilyMembers' : ActorMethod<[], Array<FamilyMember>>,
  'getAllMealOptions' : ActorMethod<[], Array<MealOption>>,
  'getAllMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getAllShoppingItems' : ActorMethod<[], Array<ShoppingItem>>,
  'getCalendarEventsByDateRange' : ActorMethod<
    [Time, Time],
    Array<CalendarEvent>
  >,
  'getCalendarEventsByMember' : ActorMethod<[bigint], Array<CalendarEvent>>,
  'getChoresByMember' : ActorMethod<[bigint], Array<Chore>>,
  'getDataCounts' : ActorMethod<
    [],
    {
      'meals' : bigint,
      'members' : bigint,
      'shoppingItems' : bigint,
      'moodEntries' : bigint,
      'events' : bigint,
      'chores' : bigint,
    }
  >,
  'getFamilyMember' : ActorMethod<[bigint], [] | [FamilyMember]>,
  'getInviteDetails' : ActorMethod<[string], InviteDetails>,
  'getMealAttendanceForDate' : ActorMethod<[Time], Array<MealAttendance>>,
  'getMealOptionsByDate' : ActorMethod<[Time], Array<MealOption>>,
  'getMemberAttendance' : ActorMethod<[Time, bigint], [] | [MealAttendance]>,
  'getMoodEntriesByDateRange' : ActorMethod<[Time, Time], Array<MoodEntry>>,
  'getMoodEntriesByMember' : ActorMethod<[bigint], Array<MoodEntry>>,
  'getMyFamily' : ActorMethod<[], Family>,
  'getMyFamilyStatus' : ActorMethod<[], FamilyStatus>,
  'getMyMember' : ActorMethod<[], FamilyMember>,
  'getShoppingItemsByCategory' : ActorMethod<[string], Array<ShoppingItem>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'joinFamilyWithCode' : ActorMethod<
    [string],
    { 'memberId' : bigint, 'familyId' : bigint }
  >,
  'regenerateInviteCode' : ActorMethod<[bigint], string>,
  'selectMeal' : ActorMethod<[bigint], MealOption>,
  'setMealAttendance' : ActorMethod<[Time, bigint, boolean], MealAttendance>,
  'toggleChoreComplete' : ActorMethod<[bigint], Chore>,
  'toggleShoppingItemComplete' : ActorMethod<[bigint], ShoppingItem>,
  'updateCalendarEvent' : ActorMethod<
    [bigint, string, string, Time, Time, Array<bigint>, string],
    CalendarEvent
  >,
  'updateChore' : ActorMethod<
    [bigint, string, string, [] | [bigint], Time, string],
    Chore
  >,
  'updateFamilyMember' : ActorMethod<
    [bigint, string, string, string],
    FamilyMember
  >,
  'updateMemberRole' : ActorMethod<[bigint, string], FamilyMember>,
  'updateMoodEntry' : ActorMethod<[bigint, string, string], MoodEntry>,
  'updateShoppingItem' : ActorMethod<
    [bigint, string, string, string],
    ShoppingItem
  >,
  'voteForMeal' : ActorMethod<[bigint, bigint], MealOption>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];