/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FamilyMember = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Opt(IDL.Principal),
  'isLinked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
  'role' : IDL.Text,
  'inviteCode' : IDL.Opt(IDL.Text),
  'avatarEmoji' : IDL.Text,
  'familyId' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'addedBy' : IDL.Nat,
  'quantity' : IDL.Text,
  'category' : IDL.Text,
});
export const MoodEntry = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'date' : Time,
  'mood' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : Time,
});
export const MealOption = IDL.Record({
  'id' : IDL.Nat,
  'isSelected' : IDL.Bool,
  'scheduledDate' : Time,
  'votes' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'proposedBy' : IDL.Nat,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'memberIds' : IDL.Vec(IDL.Nat),
  'startDate' : Time,
  'eventType' : IDL.Text,
});
export const Chore = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Nat),
  'isCompleted' : IDL.Bool,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : IDL.Text,
  'recurrence' : IDL.Text,
});
export const SampleData = IDL.Record({
  'members' : IDL.Vec(FamilyMember),
  'shoppingItems' : IDL.Vec(ShoppingItem),
  'moodEntries' : IDL.Vec(MoodEntry),
  'mealOptions' : IDL.Vec(MealOption),
  'events' : IDL.Vec(CalendarEvent),
  'chores' : IDL.Vec(Chore),
});
export const InviteDetails = IDL.Record({
  'familyName' : IDL.Text,
  'memberColor' : IDL.Text,
  'memberName' : IDL.Text,
  'memberAvatarEmoji' : IDL.Text,
});
export const MealAttendance = IDL.Record({
  'memberId' : IDL.Nat,
  'date' : Time,
  'attending' : IDL.Bool,
});
export const Family = IDL.Record({
  'id' : IDL.Nat,
  'adminPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const FamilyStatus = IDL.Variant({
  'NotLinked' : IDL.Null,
  'FamilyMember' : IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat }),
  'FamilyAdmin' : IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat }),
});

export const idlService = IDL.Service({
  'addCalendarEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, IDL.Vec(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addChore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addFamilyMemberWithInvite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'memberId' : IDL.Nat, 'inviteCode' : IDL.Text })],
      [],
    ),
  'addMealOption' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time],
      [IDL.Nat],
      [],
    ),
  'addMoodEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Time], [IDL.Nat], []),
  'addShoppingItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'clearAllData' : IDL.Func([], [IDL.Bool], []),
  'clearCompletedShoppingItems' : IDL.Func([], [IDL.Nat], []),
  'createFamily' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat })],
      [],
    ),
  'deleteCalendarEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFamilyMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMealOption' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMoodEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteShoppingItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateSampleData' : IDL.Func([], [SampleData], []),
  'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getAllChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
  'getAllFamilyMembers' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
  'getAllMealOptions' : IDL.Func([], [IDL.Vec(MealOption)], ['query']),
  'getAllMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getAllShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'getCalendarEventsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getCalendarEventsByMember' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getChoresByMember' : IDL.Func([IDL.Nat], [IDL.Vec(Chore)], ['query']),
  'getDataCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'meals' : IDL.Nat,
          'members' : IDL.Nat,
          'shoppingItems' : IDL.Nat,
          'moodEntries' : IDL.Nat,
          'events' : IDL.Nat,
          'chores' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFamilyMember' : IDL.Func([IDL.Nat], [IDL.Opt(FamilyMember)], ['query']),
  'getInviteDetails' : IDL.Func([IDL.Text], [InviteDetails], ['query']),
  'getMealAttendanceForDate' : IDL.Func(
      [Time],
      [IDL.Vec(MealAttendance)],
      ['query'],
    ),
  'getMealOptionsByDate' : IDL.Func([Time], [IDL.Vec(MealOption)], ['query']),
  'getMemberAttendance' : IDL.Func(
      [Time, IDL.Nat],
      [IDL.Opt(MealAttendance)],
      ['query'],
    ),
  'getMoodEntriesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getMoodEntriesByMember' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getMyFamily' : IDL.Func([], [Family], ['query']),
  'getMyFamilyStatus' : IDL.Func([], [FamilyStatus], ['query']),
  'getMyMember' : IDL.Func([], [FamilyMember], ['query']),
  'getShoppingItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShoppingItem)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinFamilyWithCode' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat })],
      [],
    ),
  'regenerateInviteCode' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'selectMeal' : IDL.Func([IDL.Nat], [MealOption], []),
  'setMealAttendance' : IDL.Func(
      [Time, IDL.Nat, IDL.Bool],
      [MealAttendance],
      [],
    ),
  'toggleChoreComplete' : IDL.Func([IDL.Nat], [Chore], []),
  'toggleShoppingItemComplete' : IDL.Func([IDL.Nat], [ShoppingItem], []),
  'updateCalendarEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, Time, IDL.Vec(IDL.Nat), IDL.Text],
      [CalendarEvent],
      [],
    ),
  'updateChore' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), Time, IDL.Text],
      [Chore],
      [],
    ),
  'updateFamilyMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [FamilyMember],
      [],
    ),
  'updateMemberRole' : IDL.Func([IDL.Nat, IDL.Text], [FamilyMember], []),
  'updateMoodEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [MoodEntry], []),
  'updateShoppingItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [ShoppingItem],
      [],
    ),
  'voteForMeal' : IDL.Func([IDL.Nat, IDL.Nat], [MealOption], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FamilyMember = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Opt(IDL.Principal),
    'isLinked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
    'role' : IDL.Text,
    'inviteCode' : IDL.Opt(IDL.Text),
    'avatarEmoji' : IDL.Text,
    'familyId' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'addedBy' : IDL.Nat,
    'quantity' : IDL.Text,
    'category' : IDL.Text,
  });
  const MoodEntry = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'date' : Time,
    'mood' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : Time,
  });
  const MealOption = IDL.Record({
    'id' : IDL.Nat,
    'isSelected' : IDL.Bool,
    'scheduledDate' : Time,
    'votes' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'proposedBy' : IDL.Nat,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'memberIds' : IDL.Vec(IDL.Nat),
    'startDate' : Time,
    'eventType' : IDL.Text,
  });
  const Chore = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Nat),
    'isCompleted' : IDL.Bool,
    'createdAt' : Time,
    'dueDate' : Time,
    'description' : IDL.Text,
    'recurrence' : IDL.Text,
  });
  const SampleData = IDL.Record({
    'members' : IDL.Vec(FamilyMember),
    'shoppingItems' : IDL.Vec(ShoppingItem),
    'moodEntries' : IDL.Vec(MoodEntry),
    'mealOptions' : IDL.Vec(MealOption),
    'events' : IDL.Vec(CalendarEvent),
    'chores' : IDL.Vec(Chore),
  });
  const InviteDetails = IDL.Record({
    'familyName' : IDL.Text,
    'memberColor' : IDL.Text,
    'memberName' : IDL.Text,
    'memberAvatarEmoji' : IDL.Text,
  });
  const MealAttendance = IDL.Record({
    'memberId' : IDL.Nat,
    'date' : Time,
    'attending' : IDL.Bool,
  });
  const Family = IDL.Record({
    'id' : IDL.Nat,
    'adminPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const FamilyStatus = IDL.Variant({
    'NotLinked' : IDL.Null,
    'FamilyMember' : IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat }),
    'FamilyAdmin' : IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat }),
  });
  
  return IDL.Service({
    'addCalendarEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Vec(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addChore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addFamilyMemberWithInvite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'memberId' : IDL.Nat, 'inviteCode' : IDL.Text })],
        [],
      ),
    'addMealOption' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time],
        [IDL.Nat],
        [],
      ),
    'addMoodEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'addShoppingItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'clearAllData' : IDL.Func([], [IDL.Bool], []),
    'clearCompletedShoppingItems' : IDL.Func([], [IDL.Nat], []),
    'createFamily' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat })],
        [],
      ),
    'deleteCalendarEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFamilyMember' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMealOption' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMoodEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteShoppingItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateSampleData' : IDL.Func([], [SampleData], []),
    'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getAllChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
    'getAllFamilyMembers' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
    'getAllMealOptions' : IDL.Func([], [IDL.Vec(MealOption)], ['query']),
    'getAllMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getAllShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'getCalendarEventsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getCalendarEventsByMember' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getChoresByMember' : IDL.Func([IDL.Nat], [IDL.Vec(Chore)], ['query']),
    'getDataCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'meals' : IDL.Nat,
            'members' : IDL.Nat,
            'shoppingItems' : IDL.Nat,
            'moodEntries' : IDL.Nat,
            'events' : IDL.Nat,
            'chores' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFamilyMember' : IDL.Func([IDL.Nat], [IDL.Opt(FamilyMember)], ['query']),
    'getInviteDetails' : IDL.Func([IDL.Text], [InviteDetails], ['query']),
    'getMealAttendanceForDate' : IDL.Func(
        [Time],
        [IDL.Vec(MealAttendance)],
        ['query'],
      ),
    'getMealOptionsByDate' : IDL.Func([Time], [IDL.Vec(MealOption)], ['query']),
    'getMemberAttendance' : IDL.Func(
        [Time, IDL.Nat],
        [IDL.Opt(MealAttendance)],
        ['query'],
      ),
    'getMoodEntriesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMoodEntriesByMember' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMyFamily' : IDL.Func([], [Family], ['query']),
    'getMyFamilyStatus' : IDL.Func([], [FamilyStatus], ['query']),
    'getMyMember' : IDL.Func([], [FamilyMember], ['query']),
    'getShoppingItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShoppingItem)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinFamilyWithCode' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'memberId' : IDL.Nat, 'familyId' : IDL.Nat })],
        [],
      ),
    'regenerateInviteCode' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'selectMeal' : IDL.Func([IDL.Nat], [MealOption], []),
    'setMealAttendance' : IDL.Func(
        [Time, IDL.Nat, IDL.Bool],
        [MealAttendance],
        [],
      ),
    'toggleChoreComplete' : IDL.Func([IDL.Nat], [Chore], []),
    'toggleShoppingItemComplete' : IDL.Func([IDL.Nat], [ShoppingItem], []),
    'updateCalendarEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, Time, IDL.Vec(IDL.Nat), IDL.Text],
        [CalendarEvent],
        [],
      ),
    'updateChore' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), Time, IDL.Text],
        [Chore],
        [],
      ),
    'updateFamilyMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [FamilyMember],
        [],
      ),
    'updateMemberRole' : IDL.Func([IDL.Nat, IDL.Text], [FamilyMember], []),
    'updateMoodEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [MoodEntry],
        [],
      ),
    'updateShoppingItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [ShoppingItem],
        [],
      ),
    'voteForMeal' : IDL.Func([IDL.Nat, IDL.Nat], [MealOption], []),
  });
};

export const init = ({ IDL }) => { return []; };